/*
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import umlrtsyntesizer.services.ConstLangGrammarAccess;

@SuppressWarnings("all")
public class ConstLangSyntacticSequencer extends AbstractSyntacticSequencer {

	protected ConstLangGrammarAccess grammarAccess;
	protected AbstractElementAlias match_MessageConstraint_PreKeyword_5_1_0_q;
	protected AbstractElementAlias match_PrimaryExpression_LeftParenthesisKeyword_1_0_a;
	protected AbstractElementAlias match_PrimaryExpression_LeftParenthesisKeyword_1_0_p;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (ConstLangGrammarAccess) access;
		match_MessageConstraint_PreKeyword_5_1_0_q = new TokenAlias(false, true, grammarAccess.getMessageConstraintAccess().getPreKeyword_5_1_0());
		match_PrimaryExpression_LeftParenthesisKeyword_1_0_a = new TokenAlias(true, true, grammarAccess.getPrimaryExpressionAccess().getLeftParenthesisKeyword_1_0());
		match_PrimaryExpression_LeftParenthesisKeyword_1_0_p = new TokenAlias(true, false, grammarAccess.getPrimaryExpressionAccess().getLeftParenthesisKeyword_1_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_MessageConstraint_PreKeyword_5_1_0_q.equals(syntax))
				emit_MessageConstraint_PreKeyword_5_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PrimaryExpression_LeftParenthesisKeyword_1_0_a.equals(syntax))
				emit_PrimaryExpression_LeftParenthesisKeyword_1_0_a(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_PrimaryExpression_LeftParenthesisKeyword_1_0_p.equals(syntax))
				emit_PrimaryExpression_LeftParenthesisKeyword_1_0_p(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'Pre:'?
	 *
	 * This ambiguous syntax occurs at:
	 *     name=ID '(' ')' (ambiguity) 'Post:' postConstraints=Expression
	 *     params+=Attribute ')' (ambiguity) 'Post:' postConstraints=Expression
	 */
	protected void emit_MessageConstraint_PreKeyword_5_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('*
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '-' exp=Unary
	 *     (rule start) (ambiguity) 'not' exp=PrimaryExpression
	 *     (rule start) (ambiguity) boolLiteral=BOOLEAN
	 *     (rule start) (ambiguity) intLiteral=INT
	 *     (rule start) (ambiguity) intPart=INT
	 *     (rule start) (ambiguity) ref=[Attribute|ID]
	 *     (rule start) (ambiguity) {Addition.left=}
	 *     (rule start) (ambiguity) {AndExpression.left=}
	 *     (rule start) (ambiguity) {Assign.left=}
	 *     (rule start) (ambiguity) {Divide.left=}
	 *     (rule start) (ambiguity) {EQ.left=}
	 *     (rule start) (ambiguity) {GE.left=}
	 *     (rule start) (ambiguity) {GT.left=}
	 *     (rule start) (ambiguity) {Implie.left=}
	 *     (rule start) (ambiguity) {LE.left=}
	 *     (rule start) (ambiguity) {LT.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Modulo.left=}
	 *     (rule start) (ambiguity) {Multiplication.left=}
	 *     (rule start) (ambiguity) {NE.left=}
	 *     (rule start) (ambiguity) {OrExpression.left=}
	 */
	protected void emit_PrimaryExpression_LeftParenthesisKeyword_1_0_a(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     '('+
	 *
	 * This ambiguous syntax occurs at:
	 *     (rule start) (ambiguity) '-' exp=Unary
	 *     (rule start) (ambiguity) 'not' exp=PrimaryExpression
	 *     (rule start) (ambiguity) {Addition.left=}
	 *     (rule start) (ambiguity) {AndExpression.left=}
	 *     (rule start) (ambiguity) {Assign.left=}
	 *     (rule start) (ambiguity) {Divide.left=}
	 *     (rule start) (ambiguity) {EQ.left=}
	 *     (rule start) (ambiguity) {GE.left=}
	 *     (rule start) (ambiguity) {GT.left=}
	 *     (rule start) (ambiguity) {Implie.left=}
	 *     (rule start) (ambiguity) {LE.left=}
	 *     (rule start) (ambiguity) {LT.left=}
	 *     (rule start) (ambiguity) {Minus.left=}
	 *     (rule start) (ambiguity) {Modulo.left=}
	 *     (rule start) (ambiguity) {Multiplication.left=}
	 *     (rule start) (ambiguity) {NE.left=}
	 *     (rule start) (ambiguity) {OrExpression.left=}
	 */
	protected void emit_PrimaryExpression_LeftParenthesisKeyword_1_0_p(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
