/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer;

import umlrtsyntesizer.ConstLangStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ConstLangStandaloneSetup extends ConstLangStandaloneSetupGenerated {
  public static void doSetup() {
    new ConstLangStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
