/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.validation;

import umlrtsyntesizer.validation.AbstractConstLangValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class ConstLangValidator extends AbstractConstLangValidator {
}
