/*
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import umlrtsyntesizer.parser.antlr.internal.InternalExecTracesParser;
import umlrtsyntesizer.services.ExecTracesGrammarAccess;

public class ExecTracesParser extends AbstractAntlrParser {

	@Inject
	private ExecTracesGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalExecTracesParser createParser(XtextTokenStream stream) {
		return new InternalExecTracesParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "ExecTraces";
	}

	public ExecTracesGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ExecTracesGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
