/*
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExecTracesStandaloneSetup extends ExecTracesStandaloneSetupGenerated {

	def static void doSetup() {
		new ExecTracesStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
