/*
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractConstLangScopeProvider extends DelegatingScopeProvider {
}
