/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.constLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link umlrtsyntesizer.constLang.BoolLiteral#getBoolLiteral <em>Bool Literal</em>}</li>
 * </ul>
 *
 * @see umlrtsyntesizer.constLang.ConstLangPackage#getBoolLiteral()
 * @model
 * @generated
 */
public interface BoolLiteral extends Literal
{
  /**
   * Returns the value of the '<em><b>Bool Literal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bool Literal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool Literal</em>' attribute.
   * @see #setBoolLiteral(String)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getBoolLiteral_BoolLiteral()
   * @model
   * @generated
   */
  String getBoolLiteral();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.BoolLiteral#getBoolLiteral <em>Bool Literal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool Literal</em>' attribute.
   * @see #getBoolLiteral()
   * @generated
   */
  void setBoolLiteral(String value);

} // BoolLiteral
