/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.constLang;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see umlrtsyntesizer.constLang.ConstLangFactory
 * @model kind="package"
 * @generated
 */
public interface ConstLangPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "constLang";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.ConstLang.umlrtsyntesizer";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "constLang";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  ConstLangPackage eINSTANCE = umlrtsyntesizer.constLang.impl.ConstLangPackageImpl.init();

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.ContextImpl <em>Context</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.ContextImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getContext()
   * @generated
   */
  int CONTEXT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__NAME = 0;

  /**
   * The feature id for the '<em><b>Attributes</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__ATTRIBUTES = 1;

  /**
   * The feature id for the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__INIT = 2;

  /**
   * The feature id for the '<em><b>System Invariants</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__SYSTEM_INVARIANTS = 3;

  /**
   * The feature id for the '<em><b>Message Constraints</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT__MESSAGE_CONSTRAINTS = 4;

  /**
   * The number of structural features of the '<em>Context</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONTEXT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.InitImpl <em>Init</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.InitImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getInit()
   * @generated
   */
  int INIT = 1;

  /**
   * The feature id for the '<em><b>Expressions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INIT__EXPRESSIONS = 0;

  /**
   * The number of structural features of the '<em>Init</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INIT_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.SystemInvariantImpl <em>System Invariant</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.SystemInvariantImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getSystemInvariant()
   * @generated
   */
  int SYSTEM_INVARIANT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_INVARIANT__NAME = 0;

  /**
   * The feature id for the '<em><b>Invariant Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_INVARIANT__INVARIANT_EXP = 1;

  /**
   * The number of structural features of the '<em>System Invariant</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SYSTEM_INVARIANT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.MessageConstraintImpl <em>Message Constraint</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.MessageConstraintImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getMessageConstraint()
   * @generated
   */
  int MESSAGE_CONSTRAINT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_CONSTRAINT__NAME = 0;

  /**
   * The feature id for the '<em><b>Params</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_CONSTRAINT__PARAMS = 1;

  /**
   * The feature id for the '<em><b>Where To Apply</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_CONSTRAINT__WHERE_TO_APPLY = 2;

  /**
   * The feature id for the '<em><b>Pre Constraints</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_CONSTRAINT__PRE_CONSTRAINTS = 3;

  /**
   * The feature id for the '<em><b>Post Constraints</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_CONSTRAINT__POST_CONSTRAINTS = 4;

  /**
   * The number of structural features of the '<em>Message Constraint</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_CONSTRAINT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.RangeImpl <em>Range</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.RangeImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getRange()
   * @generated
   */
  int RANGE = 4;

  /**
   * The feature id for the '<em><b>From</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__FROM = 0;

  /**
   * The feature id for the '<em><b>To</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE__TO = 1;

  /**
   * The number of structural features of the '<em>Range</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RANGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.ValueImpl <em>Value</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.ValueImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getValue()
   * @generated
   */
  int VALUE = 5;

  /**
   * The feature id for the '<em><b>Minues</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__MINUES = 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__VALUE = 1;

  /**
   * The feature id for the '<em><b>Fixed Point Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE__FIXED_POINT_VALUE = 2;

  /**
   * The number of structural features of the '<em>Value</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VALUE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.ExpressionImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 9;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.LiteralImpl <em>Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.LiteralImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getLiteral()
   * @generated
   */
  int LITERAL = 13;

  /**
   * The number of structural features of the '<em>Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.RealLiteralImpl <em>Real Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.RealLiteralImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getRealLiteral()
   * @generated
   */
  int REAL_LITERAL = 6;

  /**
   * The feature id for the '<em><b>Int Part</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL__INT_PART = LITERAL_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Decimal Part</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL__DECIMAL_PART = LITERAL_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Real Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int REAL_LITERAL_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.AttributeImpl <em>Attribute</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.AttributeImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getAttribute()
   * @generated
   */
  int ATTRIBUTE = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__NAME = 0;

  /**
   * The feature id for the '<em><b>Property Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__PROPERTY_TYPE = 1;

  /**
   * The feature id for the '<em><b>Range</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE__RANGE = 2;

  /**
   * The number of structural features of the '<em>Attribute</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ATTRIBUTE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.ParamImpl <em>Param</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.ParamImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getParam()
   * @generated
   */
  int PARAM = 8;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__NAME = 0;

  /**
   * The feature id for the '<em><b>Property Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM__PROPERTY_TYPE = 1;

  /**
   * The number of structural features of the '<em>Param</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAM_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.NotBooleanExpressionImpl <em>Not Boolean Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.NotBooleanExpressionImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getNotBooleanExpression()
   * @generated
   */
  int NOT_BOOLEAN_EXPRESSION = 10;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_BOOLEAN_EXPRESSION__EXP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Not Boolean Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NOT_BOOLEAN_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.ParameterImpl <em>Parameter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.ParameterImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getParameter()
   * @generated
   */
  int PARAMETER = 11;

  /**
   * The feature id for the '<em><b>Paramname</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER__PARAMNAME = 0;

  /**
   * The number of structural features of the '<em>Parameter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARAMETER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.IdentifierImpl <em>Identifier</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.IdentifierImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getIdentifier()
   * @generated
   */
  int IDENTIFIER = 12;

  /**
   * The feature id for the '<em><b>Ref</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFIER__REF = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Identifier</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IDENTIFIER_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.IntLiteralImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 14;

  /**
   * The feature id for the '<em><b>Int Literal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__INT_LITERAL = LITERAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.BoolLiteralImpl <em>Bool Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.BoolLiteralImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getBoolLiteral()
   * @generated
   */
  int BOOL_LITERAL = 15;

  /**
   * The feature id for the '<em><b>Bool Literal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_LITERAL__BOOL_LITERAL = LITERAL_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Bool Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BOOL_LITERAL_FEATURE_COUNT = LITERAL_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.AssignImpl <em>Assign</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.AssignImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getAssign()
   * @generated
   */
  int ASSIGN = 16;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Assign</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ASSIGN_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.ImplieImpl <em>Implie</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.ImplieImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getImplie()
   * @generated
   */
  int IMPLIE = 17;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLIE__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLIE__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Implie</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int IMPLIE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.OrExpressionImpl <em>Or Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.OrExpressionImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getOrExpression()
   * @generated
   */
  int OR_EXPRESSION = 18;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Or Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.AndExpressionImpl <em>And Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.AndExpressionImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getAndExpression()
   * @generated
   */
  int AND_EXPRESSION = 19;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>And Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AND_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.GTImpl <em>GT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.GTImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getGT()
   * @generated
   */
  int GT = 20;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT__REST = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>GT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.LTImpl <em>LT</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.LTImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getLT()
   * @generated
   */
  int LT = 21;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT__REST = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>LT</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LT_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.GEImpl <em>GE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.GEImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getGE()
   * @generated
   */
  int GE = 22;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GE__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GE__REST = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>GE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int GE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.LEImpl <em>LE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.LEImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getLE()
   * @generated
   */
  int LE = 23;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LE__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LE__REST = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>LE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.EQImpl <em>EQ</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.EQImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getEQ()
   * @generated
   */
  int EQ = 24;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQ__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQ__REST = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>EQ</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EQ_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.NEImpl <em>NE</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.NEImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getNE()
   * @generated
   */
  int NE = 25;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NE__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Rest</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NE__REST = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>NE</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int NE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.AdditionImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 26;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.MinusImpl <em>Minus</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.MinusImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getMinus()
   * @generated
   */
  int MINUS = 27;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Minus</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MINUS_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.MultiplicationImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 28;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.DivideImpl <em>Divide</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.DivideImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getDivide()
   * @generated
   */
  int DIVIDE = 29;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Divide</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DIVIDE_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.ModuloImpl <em>Modulo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.ModuloImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getModulo()
   * @generated
   */
  int MODULO = 30;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULO__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULO__RIGHT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Modulo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MODULO_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.impl.UnaryExpressionImpl <em>Unary Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.impl.UnaryExpressionImpl
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getUnaryExpression()
   * @generated
   */
  int UNARY_EXPRESSION = 31;

  /**
   * The feature id for the '<em><b>Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXPRESSION__EXP = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Unary Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int UNARY_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.VarType <em>Var Type</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.VarType
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getVarType()
   * @generated
   */
  int VAR_TYPE = 32;

  /**
   * The meta object id for the '{@link umlrtsyntesizer.constLang.WhereToApplyEnum <em>Where To Apply Enum</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see umlrtsyntesizer.constLang.WhereToApplyEnum
   * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getWhereToApplyEnum()
   * @generated
   */
  int WHERE_TO_APPLY_ENUM = 33;


  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Context <em>Context</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Context</em>'.
   * @see umlrtsyntesizer.constLang.Context
   * @generated
   */
  EClass getContext();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.Context#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see umlrtsyntesizer.constLang.Context#getName()
   * @see #getContext()
   * @generated
   */
  EAttribute getContext_Name();

  /**
   * Returns the meta object for the containment reference list '{@link umlrtsyntesizer.constLang.Context#getAttributes <em>Attributes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Attributes</em>'.
   * @see umlrtsyntesizer.constLang.Context#getAttributes()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Attributes();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Context#getInit <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Init</em>'.
   * @see umlrtsyntesizer.constLang.Context#getInit()
   * @see #getContext()
   * @generated
   */
  EReference getContext_Init();

  /**
   * Returns the meta object for the containment reference list '{@link umlrtsyntesizer.constLang.Context#getSystemInvariants <em>System Invariants</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>System Invariants</em>'.
   * @see umlrtsyntesizer.constLang.Context#getSystemInvariants()
   * @see #getContext()
   * @generated
   */
  EReference getContext_SystemInvariants();

  /**
   * Returns the meta object for the containment reference list '{@link umlrtsyntesizer.constLang.Context#getMessageConstraints <em>Message Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Message Constraints</em>'.
   * @see umlrtsyntesizer.constLang.Context#getMessageConstraints()
   * @see #getContext()
   * @generated
   */
  EReference getContext_MessageConstraints();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Init <em>Init</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Init</em>'.
   * @see umlrtsyntesizer.constLang.Init
   * @generated
   */
  EClass getInit();

  /**
   * Returns the meta object for the containment reference list '{@link umlrtsyntesizer.constLang.Init#getExpressions <em>Expressions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Expressions</em>'.
   * @see umlrtsyntesizer.constLang.Init#getExpressions()
   * @see #getInit()
   * @generated
   */
  EReference getInit_Expressions();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.SystemInvariant <em>System Invariant</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>System Invariant</em>'.
   * @see umlrtsyntesizer.constLang.SystemInvariant
   * @generated
   */
  EClass getSystemInvariant();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.SystemInvariant#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see umlrtsyntesizer.constLang.SystemInvariant#getName()
   * @see #getSystemInvariant()
   * @generated
   */
  EAttribute getSystemInvariant_Name();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.SystemInvariant#getInvariantExp <em>Invariant Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Invariant Exp</em>'.
   * @see umlrtsyntesizer.constLang.SystemInvariant#getInvariantExp()
   * @see #getSystemInvariant()
   * @generated
   */
  EReference getSystemInvariant_InvariantExp();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.MessageConstraint <em>Message Constraint</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Message Constraint</em>'.
   * @see umlrtsyntesizer.constLang.MessageConstraint
   * @generated
   */
  EClass getMessageConstraint();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.MessageConstraint#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see umlrtsyntesizer.constLang.MessageConstraint#getName()
   * @see #getMessageConstraint()
   * @generated
   */
  EAttribute getMessageConstraint_Name();

  /**
   * Returns the meta object for the containment reference list '{@link umlrtsyntesizer.constLang.MessageConstraint#getParams <em>Params</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Params</em>'.
   * @see umlrtsyntesizer.constLang.MessageConstraint#getParams()
   * @see #getMessageConstraint()
   * @generated
   */
  EReference getMessageConstraint_Params();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.MessageConstraint#getWhereToApply <em>Where To Apply</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Where To Apply</em>'.
   * @see umlrtsyntesizer.constLang.MessageConstraint#getWhereToApply()
   * @see #getMessageConstraint()
   * @generated
   */
  EAttribute getMessageConstraint_WhereToApply();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.MessageConstraint#getPreConstraints <em>Pre Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Pre Constraints</em>'.
   * @see umlrtsyntesizer.constLang.MessageConstraint#getPreConstraints()
   * @see #getMessageConstraint()
   * @generated
   */
  EReference getMessageConstraint_PreConstraints();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.MessageConstraint#getPostConstraints <em>Post Constraints</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Post Constraints</em>'.
   * @see umlrtsyntesizer.constLang.MessageConstraint#getPostConstraints()
   * @see #getMessageConstraint()
   * @generated
   */
  EReference getMessageConstraint_PostConstraints();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Range <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Range</em>'.
   * @see umlrtsyntesizer.constLang.Range
   * @generated
   */
  EClass getRange();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Range#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>From</em>'.
   * @see umlrtsyntesizer.constLang.Range#getFrom()
   * @see #getRange()
   * @generated
   */
  EReference getRange_From();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Range#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>To</em>'.
   * @see umlrtsyntesizer.constLang.Range#getTo()
   * @see #getRange()
   * @generated
   */
  EReference getRange_To();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Value <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Value</em>'.
   * @see umlrtsyntesizer.constLang.Value
   * @generated
   */
  EClass getValue();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.Value#isMinues <em>Minues</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Minues</em>'.
   * @see umlrtsyntesizer.constLang.Value#isMinues()
   * @see #getValue()
   * @generated
   */
  EAttribute getValue_Minues();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.Value#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see umlrtsyntesizer.constLang.Value#getValue()
   * @see #getValue()
   * @generated
   */
  EAttribute getValue_Value();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Value#getFixedPointValue <em>Fixed Point Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Fixed Point Value</em>'.
   * @see umlrtsyntesizer.constLang.Value#getFixedPointValue()
   * @see #getValue()
   * @generated
   */
  EReference getValue_FixedPointValue();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.RealLiteral <em>Real Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Real Literal</em>'.
   * @see umlrtsyntesizer.constLang.RealLiteral
   * @generated
   */
  EClass getRealLiteral();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.RealLiteral#getIntPart <em>Int Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int Part</em>'.
   * @see umlrtsyntesizer.constLang.RealLiteral#getIntPart()
   * @see #getRealLiteral()
   * @generated
   */
  EAttribute getRealLiteral_IntPart();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.RealLiteral#getDecimalPart <em>Decimal Part</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Decimal Part</em>'.
   * @see umlrtsyntesizer.constLang.RealLiteral#getDecimalPart()
   * @see #getRealLiteral()
   * @generated
   */
  EAttribute getRealLiteral_DecimalPart();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Attribute <em>Attribute</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Attribute</em>'.
   * @see umlrtsyntesizer.constLang.Attribute
   * @generated
   */
  EClass getAttribute();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.Attribute#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see umlrtsyntesizer.constLang.Attribute#getName()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_Name();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.Attribute#getPropertyType <em>Property Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property Type</em>'.
   * @see umlrtsyntesizer.constLang.Attribute#getPropertyType()
   * @see #getAttribute()
   * @generated
   */
  EAttribute getAttribute_PropertyType();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Attribute#getRange <em>Range</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Range</em>'.
   * @see umlrtsyntesizer.constLang.Attribute#getRange()
   * @see #getAttribute()
   * @generated
   */
  EReference getAttribute_Range();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Param <em>Param</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Param</em>'.
   * @see umlrtsyntesizer.constLang.Param
   * @generated
   */
  EClass getParam();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.Param#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see umlrtsyntesizer.constLang.Param#getName()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_Name();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.Param#getPropertyType <em>Property Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Property Type</em>'.
   * @see umlrtsyntesizer.constLang.Param#getPropertyType()
   * @see #getParam()
   * @generated
   */
  EAttribute getParam_PropertyType();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see umlrtsyntesizer.constLang.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.NotBooleanExpression <em>Not Boolean Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Not Boolean Expression</em>'.
   * @see umlrtsyntesizer.constLang.NotBooleanExpression
   * @generated
   */
  EClass getNotBooleanExpression();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.NotBooleanExpression#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see umlrtsyntesizer.constLang.NotBooleanExpression#getExp()
   * @see #getNotBooleanExpression()
   * @generated
   */
  EReference getNotBooleanExpression_Exp();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Parameter <em>Parameter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Parameter</em>'.
   * @see umlrtsyntesizer.constLang.Parameter
   * @generated
   */
  EClass getParameter();

  /**
   * Returns the meta object for the reference '{@link umlrtsyntesizer.constLang.Parameter#getParamname <em>Paramname</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Paramname</em>'.
   * @see umlrtsyntesizer.constLang.Parameter#getParamname()
   * @see #getParameter()
   * @generated
   */
  EReference getParameter_Paramname();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Identifier <em>Identifier</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Identifier</em>'.
   * @see umlrtsyntesizer.constLang.Identifier
   * @generated
   */
  EClass getIdentifier();

  /**
   * Returns the meta object for the reference '{@link umlrtsyntesizer.constLang.Identifier#getRef <em>Ref</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Ref</em>'.
   * @see umlrtsyntesizer.constLang.Identifier#getRef()
   * @see #getIdentifier()
   * @generated
   */
  EReference getIdentifier_Ref();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Literal <em>Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Literal</em>'.
   * @see umlrtsyntesizer.constLang.Literal
   * @generated
   */
  EClass getLiteral();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see umlrtsyntesizer.constLang.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.IntLiteral#getIntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Int Literal</em>'.
   * @see umlrtsyntesizer.constLang.IntLiteral#getIntLiteral()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_IntLiteral();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.BoolLiteral <em>Bool Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Bool Literal</em>'.
   * @see umlrtsyntesizer.constLang.BoolLiteral
   * @generated
   */
  EClass getBoolLiteral();

  /**
   * Returns the meta object for the attribute '{@link umlrtsyntesizer.constLang.BoolLiteral#getBoolLiteral <em>Bool Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Bool Literal</em>'.
   * @see umlrtsyntesizer.constLang.BoolLiteral#getBoolLiteral()
   * @see #getBoolLiteral()
   * @generated
   */
  EAttribute getBoolLiteral_BoolLiteral();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Assign <em>Assign</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Assign</em>'.
   * @see umlrtsyntesizer.constLang.Assign
   * @generated
   */
  EClass getAssign();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Assign#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.Assign#getLeft()
   * @see #getAssign()
   * @generated
   */
  EReference getAssign_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Assign#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see umlrtsyntesizer.constLang.Assign#getRight()
   * @see #getAssign()
   * @generated
   */
  EReference getAssign_Right();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Implie <em>Implie</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Implie</em>'.
   * @see umlrtsyntesizer.constLang.Implie
   * @generated
   */
  EClass getImplie();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Implie#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.Implie#getLeft()
   * @see #getImplie()
   * @generated
   */
  EReference getImplie_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Implie#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see umlrtsyntesizer.constLang.Implie#getRight()
   * @see #getImplie()
   * @generated
   */
  EReference getImplie_Right();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.OrExpression <em>Or Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Or Expression</em>'.
   * @see umlrtsyntesizer.constLang.OrExpression
   * @generated
   */
  EClass getOrExpression();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.OrExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.OrExpression#getLeft()
   * @see #getOrExpression()
   * @generated
   */
  EReference getOrExpression_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.OrExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see umlrtsyntesizer.constLang.OrExpression#getRight()
   * @see #getOrExpression()
   * @generated
   */
  EReference getOrExpression_Right();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.AndExpression <em>And Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>And Expression</em>'.
   * @see umlrtsyntesizer.constLang.AndExpression
   * @generated
   */
  EClass getAndExpression();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.AndExpression#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.AndExpression#getLeft()
   * @see #getAndExpression()
   * @generated
   */
  EReference getAndExpression_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.AndExpression#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see umlrtsyntesizer.constLang.AndExpression#getRight()
   * @see #getAndExpression()
   * @generated
   */
  EReference getAndExpression_Right();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.GT <em>GT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GT</em>'.
   * @see umlrtsyntesizer.constLang.GT
   * @generated
   */
  EClass getGT();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.GT#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.GT#getLeft()
   * @see #getGT()
   * @generated
   */
  EReference getGT_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.GT#getRest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rest</em>'.
   * @see umlrtsyntesizer.constLang.GT#getRest()
   * @see #getGT()
   * @generated
   */
  EReference getGT_Rest();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.LT <em>LT</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LT</em>'.
   * @see umlrtsyntesizer.constLang.LT
   * @generated
   */
  EClass getLT();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.LT#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.LT#getLeft()
   * @see #getLT()
   * @generated
   */
  EReference getLT_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.LT#getRest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rest</em>'.
   * @see umlrtsyntesizer.constLang.LT#getRest()
   * @see #getLT()
   * @generated
   */
  EReference getLT_Rest();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.GE <em>GE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>GE</em>'.
   * @see umlrtsyntesizer.constLang.GE
   * @generated
   */
  EClass getGE();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.GE#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.GE#getLeft()
   * @see #getGE()
   * @generated
   */
  EReference getGE_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.GE#getRest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rest</em>'.
   * @see umlrtsyntesizer.constLang.GE#getRest()
   * @see #getGE()
   * @generated
   */
  EReference getGE_Rest();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.LE <em>LE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>LE</em>'.
   * @see umlrtsyntesizer.constLang.LE
   * @generated
   */
  EClass getLE();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.LE#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.LE#getLeft()
   * @see #getLE()
   * @generated
   */
  EReference getLE_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.LE#getRest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rest</em>'.
   * @see umlrtsyntesizer.constLang.LE#getRest()
   * @see #getLE()
   * @generated
   */
  EReference getLE_Rest();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.EQ <em>EQ</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>EQ</em>'.
   * @see umlrtsyntesizer.constLang.EQ
   * @generated
   */
  EClass getEQ();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.EQ#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.EQ#getLeft()
   * @see #getEQ()
   * @generated
   */
  EReference getEQ_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.EQ#getRest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rest</em>'.
   * @see umlrtsyntesizer.constLang.EQ#getRest()
   * @see #getEQ()
   * @generated
   */
  EReference getEQ_Rest();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.NE <em>NE</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>NE</em>'.
   * @see umlrtsyntesizer.constLang.NE
   * @generated
   */
  EClass getNE();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.NE#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.NE#getLeft()
   * @see #getNE()
   * @generated
   */
  EReference getNE_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.NE#getRest <em>Rest</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Rest</em>'.
   * @see umlrtsyntesizer.constLang.NE#getRest()
   * @see #getNE()
   * @generated
   */
  EReference getNE_Rest();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see umlrtsyntesizer.constLang.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see umlrtsyntesizer.constLang.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Minus <em>Minus</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Minus</em>'.
   * @see umlrtsyntesizer.constLang.Minus
   * @generated
   */
  EClass getMinus();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Minus#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.Minus#getLeft()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Minus#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see umlrtsyntesizer.constLang.Minus#getRight()
   * @see #getMinus()
   * @generated
   */
  EReference getMinus_Right();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see umlrtsyntesizer.constLang.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see umlrtsyntesizer.constLang.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Divide <em>Divide</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Divide</em>'.
   * @see umlrtsyntesizer.constLang.Divide
   * @generated
   */
  EClass getDivide();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Divide#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.Divide#getLeft()
   * @see #getDivide()
   * @generated
   */
  EReference getDivide_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Divide#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see umlrtsyntesizer.constLang.Divide#getRight()
   * @see #getDivide()
   * @generated
   */
  EReference getDivide_Right();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.Modulo <em>Modulo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Modulo</em>'.
   * @see umlrtsyntesizer.constLang.Modulo
   * @generated
   */
  EClass getModulo();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Modulo#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see umlrtsyntesizer.constLang.Modulo#getLeft()
   * @see #getModulo()
   * @generated
   */
  EReference getModulo_Left();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.Modulo#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Right</em>'.
   * @see umlrtsyntesizer.constLang.Modulo#getRight()
   * @see #getModulo()
   * @generated
   */
  EReference getModulo_Right();

  /**
   * Returns the meta object for class '{@link umlrtsyntesizer.constLang.UnaryExpression <em>Unary Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Unary Expression</em>'.
   * @see umlrtsyntesizer.constLang.UnaryExpression
   * @generated
   */
  EClass getUnaryExpression();

  /**
   * Returns the meta object for the containment reference '{@link umlrtsyntesizer.constLang.UnaryExpression#getExp <em>Exp</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exp</em>'.
   * @see umlrtsyntesizer.constLang.UnaryExpression#getExp()
   * @see #getUnaryExpression()
   * @generated
   */
  EReference getUnaryExpression_Exp();

  /**
   * Returns the meta object for enum '{@link umlrtsyntesizer.constLang.VarType <em>Var Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Var Type</em>'.
   * @see umlrtsyntesizer.constLang.VarType
   * @generated
   */
  EEnum getVarType();

  /**
   * Returns the meta object for enum '{@link umlrtsyntesizer.constLang.WhereToApplyEnum <em>Where To Apply Enum</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Where To Apply Enum</em>'.
   * @see umlrtsyntesizer.constLang.WhereToApplyEnum
   * @generated
   */
  EEnum getWhereToApplyEnum();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  ConstLangFactory getConstLangFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.ContextImpl <em>Context</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.ContextImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getContext()
     * @generated
     */
    EClass CONTEXT = eINSTANCE.getContext();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute CONTEXT__NAME = eINSTANCE.getContext_Name();

    /**
     * The meta object literal for the '<em><b>Attributes</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__ATTRIBUTES = eINSTANCE.getContext_Attributes();

    /**
     * The meta object literal for the '<em><b>Init</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__INIT = eINSTANCE.getContext_Init();

    /**
     * The meta object literal for the '<em><b>System Invariants</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__SYSTEM_INVARIANTS = eINSTANCE.getContext_SystemInvariants();

    /**
     * The meta object literal for the '<em><b>Message Constraints</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONTEXT__MESSAGE_CONSTRAINTS = eINSTANCE.getContext_MessageConstraints();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.InitImpl <em>Init</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.InitImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getInit()
     * @generated
     */
    EClass INIT = eINSTANCE.getInit();

    /**
     * The meta object literal for the '<em><b>Expressions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INIT__EXPRESSIONS = eINSTANCE.getInit_Expressions();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.SystemInvariantImpl <em>System Invariant</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.SystemInvariantImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getSystemInvariant()
     * @generated
     */
    EClass SYSTEM_INVARIANT = eINSTANCE.getSystemInvariant();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SYSTEM_INVARIANT__NAME = eINSTANCE.getSystemInvariant_Name();

    /**
     * The meta object literal for the '<em><b>Invariant Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SYSTEM_INVARIANT__INVARIANT_EXP = eINSTANCE.getSystemInvariant_InvariantExp();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.MessageConstraintImpl <em>Message Constraint</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.MessageConstraintImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getMessageConstraint()
     * @generated
     */
    EClass MESSAGE_CONSTRAINT = eINSTANCE.getMessageConstraint();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_CONSTRAINT__NAME = eINSTANCE.getMessageConstraint_Name();

    /**
     * The meta object literal for the '<em><b>Params</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_CONSTRAINT__PARAMS = eINSTANCE.getMessageConstraint_Params();

    /**
     * The meta object literal for the '<em><b>Where To Apply</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE_CONSTRAINT__WHERE_TO_APPLY = eINSTANCE.getMessageConstraint_WhereToApply();

    /**
     * The meta object literal for the '<em><b>Pre Constraints</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_CONSTRAINT__PRE_CONSTRAINTS = eINSTANCE.getMessageConstraint_PreConstraints();

    /**
     * The meta object literal for the '<em><b>Post Constraints</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MESSAGE_CONSTRAINT__POST_CONSTRAINTS = eINSTANCE.getMessageConstraint_PostConstraints();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.RangeImpl <em>Range</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.RangeImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getRange()
     * @generated
     */
    EClass RANGE = eINSTANCE.getRange();

    /**
     * The meta object literal for the '<em><b>From</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RANGE__FROM = eINSTANCE.getRange_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RANGE__TO = eINSTANCE.getRange_To();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.ValueImpl <em>Value</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.ValueImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getValue()
     * @generated
     */
    EClass VALUE = eINSTANCE.getValue();

    /**
     * The meta object literal for the '<em><b>Minues</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__MINUES = eINSTANCE.getValue_Minues();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VALUE__VALUE = eINSTANCE.getValue_Value();

    /**
     * The meta object literal for the '<em><b>Fixed Point Value</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference VALUE__FIXED_POINT_VALUE = eINSTANCE.getValue_FixedPointValue();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.RealLiteralImpl <em>Real Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.RealLiteralImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getRealLiteral()
     * @generated
     */
    EClass REAL_LITERAL = eINSTANCE.getRealLiteral();

    /**
     * The meta object literal for the '<em><b>Int Part</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REAL_LITERAL__INT_PART = eINSTANCE.getRealLiteral_IntPart();

    /**
     * The meta object literal for the '<em><b>Decimal Part</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute REAL_LITERAL__DECIMAL_PART = eINSTANCE.getRealLiteral_DecimalPart();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.AttributeImpl <em>Attribute</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.AttributeImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getAttribute()
     * @generated
     */
    EClass ATTRIBUTE = eINSTANCE.getAttribute();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__NAME = eINSTANCE.getAttribute_Name();

    /**
     * The meta object literal for the '<em><b>Property Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ATTRIBUTE__PROPERTY_TYPE = eINSTANCE.getAttribute_PropertyType();

    /**
     * The meta object literal for the '<em><b>Range</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ATTRIBUTE__RANGE = eINSTANCE.getAttribute_Range();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.ParamImpl <em>Param</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.ParamImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getParam()
     * @generated
     */
    EClass PARAM = eINSTANCE.getParam();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__NAME = eINSTANCE.getParam_Name();

    /**
     * The meta object literal for the '<em><b>Property Type</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARAM__PROPERTY_TYPE = eINSTANCE.getParam_PropertyType();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.ExpressionImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.NotBooleanExpressionImpl <em>Not Boolean Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.NotBooleanExpressionImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getNotBooleanExpression()
     * @generated
     */
    EClass NOT_BOOLEAN_EXPRESSION = eINSTANCE.getNotBooleanExpression();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NOT_BOOLEAN_EXPRESSION__EXP = eINSTANCE.getNotBooleanExpression_Exp();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.ParameterImpl <em>Parameter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.ParameterImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getParameter()
     * @generated
     */
    EClass PARAMETER = eINSTANCE.getParameter();

    /**
     * The meta object literal for the '<em><b>Paramname</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PARAMETER__PARAMNAME = eINSTANCE.getParameter_Paramname();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.IdentifierImpl <em>Identifier</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.IdentifierImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getIdentifier()
     * @generated
     */
    EClass IDENTIFIER = eINSTANCE.getIdentifier();

    /**
     * The meta object literal for the '<em><b>Ref</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IDENTIFIER__REF = eINSTANCE.getIdentifier_Ref();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.LiteralImpl <em>Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.LiteralImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getLiteral()
     * @generated
     */
    EClass LITERAL = eINSTANCE.getLiteral();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.IntLiteralImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Int Literal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__INT_LITERAL = eINSTANCE.getIntLiteral_IntLiteral();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.BoolLiteralImpl <em>Bool Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.BoolLiteralImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getBoolLiteral()
     * @generated
     */
    EClass BOOL_LITERAL = eINSTANCE.getBoolLiteral();

    /**
     * The meta object literal for the '<em><b>Bool Literal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BOOL_LITERAL__BOOL_LITERAL = eINSTANCE.getBoolLiteral_BoolLiteral();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.AssignImpl <em>Assign</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.AssignImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getAssign()
     * @generated
     */
    EClass ASSIGN = eINSTANCE.getAssign();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGN__LEFT = eINSTANCE.getAssign_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ASSIGN__RIGHT = eINSTANCE.getAssign_Right();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.ImplieImpl <em>Implie</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.ImplieImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getImplie()
     * @generated
     */
    EClass IMPLIE = eINSTANCE.getImplie();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPLIE__LEFT = eINSTANCE.getImplie_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference IMPLIE__RIGHT = eINSTANCE.getImplie_Right();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.OrExpressionImpl <em>Or Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.OrExpressionImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getOrExpression()
     * @generated
     */
    EClass OR_EXPRESSION = eINSTANCE.getOrExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EXPRESSION__LEFT = eINSTANCE.getOrExpression_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference OR_EXPRESSION__RIGHT = eINSTANCE.getOrExpression_Right();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.AndExpressionImpl <em>And Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.AndExpressionImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getAndExpression()
     * @generated
     */
    EClass AND_EXPRESSION = eINSTANCE.getAndExpression();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EXPRESSION__LEFT = eINSTANCE.getAndExpression_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AND_EXPRESSION__RIGHT = eINSTANCE.getAndExpression_Right();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.GTImpl <em>GT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.GTImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getGT()
     * @generated
     */
    EClass GT = eINSTANCE.getGT();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GT__LEFT = eINSTANCE.getGT_Left();

    /**
     * The meta object literal for the '<em><b>Rest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GT__REST = eINSTANCE.getGT_Rest();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.LTImpl <em>LT</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.LTImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getLT()
     * @generated
     */
    EClass LT = eINSTANCE.getLT();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LT__LEFT = eINSTANCE.getLT_Left();

    /**
     * The meta object literal for the '<em><b>Rest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LT__REST = eINSTANCE.getLT_Rest();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.GEImpl <em>GE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.GEImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getGE()
     * @generated
     */
    EClass GE = eINSTANCE.getGE();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GE__LEFT = eINSTANCE.getGE_Left();

    /**
     * The meta object literal for the '<em><b>Rest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference GE__REST = eINSTANCE.getGE_Rest();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.LEImpl <em>LE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.LEImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getLE()
     * @generated
     */
    EClass LE = eINSTANCE.getLE();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LE__LEFT = eINSTANCE.getLE_Left();

    /**
     * The meta object literal for the '<em><b>Rest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LE__REST = eINSTANCE.getLE_Rest();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.EQImpl <em>EQ</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.EQImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getEQ()
     * @generated
     */
    EClass EQ = eINSTANCE.getEQ();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQ__LEFT = eINSTANCE.getEQ_Left();

    /**
     * The meta object literal for the '<em><b>Rest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EQ__REST = eINSTANCE.getEQ_Rest();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.NEImpl <em>NE</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.NEImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getNE()
     * @generated
     */
    EClass NE = eINSTANCE.getNE();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NE__LEFT = eINSTANCE.getNE_Left();

    /**
     * The meta object literal for the '<em><b>Rest</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference NE__REST = eINSTANCE.getNE_Rest();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.AdditionImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.MinusImpl <em>Minus</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.MinusImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getMinus()
     * @generated
     */
    EClass MINUS = eINSTANCE.getMinus();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__LEFT = eINSTANCE.getMinus_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MINUS__RIGHT = eINSTANCE.getMinus_Right();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.MultiplicationImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.DivideImpl <em>Divide</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.DivideImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getDivide()
     * @generated
     */
    EClass DIVIDE = eINSTANCE.getDivide();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVIDE__LEFT = eINSTANCE.getDivide_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DIVIDE__RIGHT = eINSTANCE.getDivide_Right();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.ModuloImpl <em>Modulo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.ModuloImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getModulo()
     * @generated
     */
    EClass MODULO = eINSTANCE.getModulo();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODULO__LEFT = eINSTANCE.getModulo_Left();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MODULO__RIGHT = eINSTANCE.getModulo_Right();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.impl.UnaryExpressionImpl <em>Unary Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.impl.UnaryExpressionImpl
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getUnaryExpression()
     * @generated
     */
    EClass UNARY_EXPRESSION = eINSTANCE.getUnaryExpression();

    /**
     * The meta object literal for the '<em><b>Exp</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference UNARY_EXPRESSION__EXP = eINSTANCE.getUnaryExpression_Exp();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.VarType <em>Var Type</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.VarType
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getVarType()
     * @generated
     */
    EEnum VAR_TYPE = eINSTANCE.getVarType();

    /**
     * The meta object literal for the '{@link umlrtsyntesizer.constLang.WhereToApplyEnum <em>Where To Apply Enum</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see umlrtsyntesizer.constLang.WhereToApplyEnum
     * @see umlrtsyntesizer.constLang.impl.ConstLangPackageImpl#getWhereToApplyEnum()
     * @generated
     */
    EEnum WHERE_TO_APPLY_ENUM = eINSTANCE.getWhereToApplyEnum();

  }

} //ConstLangPackage
