/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.constLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Context</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link umlrtsyntesizer.constLang.Context#getName <em>Name</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.Context#getAttributes <em>Attributes</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.Context#getInit <em>Init</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.Context#getSystemInvariants <em>System Invariants</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.Context#getMessageConstraints <em>Message Constraints</em>}</li>
 * </ul>
 *
 * @see umlrtsyntesizer.constLang.ConstLangPackage#getContext()
 * @model
 * @generated
 */
public interface Context extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getContext_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.Context#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Attributes</b></em>' containment reference list.
   * The list contents are of type {@link umlrtsyntesizer.constLang.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Attributes</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Attributes</em>' containment reference list.
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getContext_Attributes()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getAttributes();

  /**
   * Returns the value of the '<em><b>Init</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Init</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Init</em>' containment reference.
   * @see #setInit(Init)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getContext_Init()
   * @model containment="true"
   * @generated
   */
  Init getInit();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.Context#getInit <em>Init</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Init</em>' containment reference.
   * @see #getInit()
   * @generated
   */
  void setInit(Init value);

  /**
   * Returns the value of the '<em><b>System Invariants</b></em>' containment reference list.
   * The list contents are of type {@link umlrtsyntesizer.constLang.SystemInvariant}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>System Invariants</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>System Invariants</em>' containment reference list.
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getContext_SystemInvariants()
   * @model containment="true"
   * @generated
   */
  EList<SystemInvariant> getSystemInvariants();

  /**
   * Returns the value of the '<em><b>Message Constraints</b></em>' containment reference list.
   * The list contents are of type {@link umlrtsyntesizer.constLang.MessageConstraint}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Message Constraints</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Message Constraints</em>' containment reference list.
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getContext_MessageConstraints()
   * @model containment="true"
   * @generated
   */
  EList<MessageConstraint> getMessageConstraints();

} // Context
