/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.constLang;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Int Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link umlrtsyntesizer.constLang.IntLiteral#getIntLiteral <em>Int Literal</em>}</li>
 * </ul>
 *
 * @see umlrtsyntesizer.constLang.ConstLangPackage#getIntLiteral()
 * @model
 * @generated
 */
public interface IntLiteral extends Literal
{
  /**
   * Returns the value of the '<em><b>Int Literal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Int Literal</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Int Literal</em>' attribute.
   * @see #setIntLiteral(int)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getIntLiteral_IntLiteral()
   * @model
   * @generated
   */
  int getIntLiteral();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.IntLiteral#getIntLiteral <em>Int Literal</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Int Literal</em>' attribute.
   * @see #getIntLiteral()
   * @generated
   */
  void setIntLiteral(int value);

} // IntLiteral
