/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.constLang;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Message Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link umlrtsyntesizer.constLang.MessageConstraint#getName <em>Name</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.MessageConstraint#getParams <em>Params</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.MessageConstraint#getWhereToApply <em>Where To Apply</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.MessageConstraint#getPreConstraints <em>Pre Constraints</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.MessageConstraint#getPostConstraints <em>Post Constraints</em>}</li>
 * </ul>
 *
 * @see umlrtsyntesizer.constLang.ConstLangPackage#getMessageConstraint()
 * @model
 * @generated
 */
public interface MessageConstraint extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getMessageConstraint_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.MessageConstraint#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link umlrtsyntesizer.constLang.Attribute}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Params</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getMessageConstraint_Params()
   * @model containment="true"
   * @generated
   */
  EList<Attribute> getParams();

  /**
   * Returns the value of the '<em><b>Where To Apply</b></em>' attribute.
   * The literals are from the enumeration {@link umlrtsyntesizer.constLang.WhereToApplyEnum}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Where To Apply</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Where To Apply</em>' attribute.
   * @see umlrtsyntesizer.constLang.WhereToApplyEnum
   * @see #setWhereToApply(WhereToApplyEnum)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getMessageConstraint_WhereToApply()
   * @model
   * @generated
   */
  WhereToApplyEnum getWhereToApply();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.MessageConstraint#getWhereToApply <em>Where To Apply</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Where To Apply</em>' attribute.
   * @see umlrtsyntesizer.constLang.WhereToApplyEnum
   * @see #getWhereToApply()
   * @generated
   */
  void setWhereToApply(WhereToApplyEnum value);

  /**
   * Returns the value of the '<em><b>Pre Constraints</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Pre Constraints</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pre Constraints</em>' containment reference.
   * @see #setPreConstraints(Expression)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getMessageConstraint_PreConstraints()
   * @model containment="true"
   * @generated
   */
  Expression getPreConstraints();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.MessageConstraint#getPreConstraints <em>Pre Constraints</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pre Constraints</em>' containment reference.
   * @see #getPreConstraints()
   * @generated
   */
  void setPreConstraints(Expression value);

  /**
   * Returns the value of the '<em><b>Post Constraints</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Post Constraints</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Post Constraints</em>' containment reference.
   * @see #setPostConstraints(Expression)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getMessageConstraint_PostConstraints()
   * @model containment="true"
   * @generated
   */
  Expression getPostConstraints();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.MessageConstraint#getPostConstraints <em>Post Constraints</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Post Constraints</em>' containment reference.
   * @see #getPostConstraints()
   * @generated
   */
  void setPostConstraints(Expression value);

} // MessageConstraint
