/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.constLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Parameter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link umlrtsyntesizer.constLang.Parameter#getParamname <em>Paramname</em>}</li>
 * </ul>
 *
 * @see umlrtsyntesizer.constLang.ConstLangPackage#getParameter()
 * @model
 * @generated
 */
public interface Parameter extends EObject
{
  /**
   * Returns the value of the '<em><b>Paramname</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Paramname</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Paramname</em>' reference.
   * @see #setParamname(Param)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getParameter_Paramname()
   * @model
   * @generated
   */
  Param getParamname();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.Parameter#getParamname <em>Paramname</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Paramname</em>' reference.
   * @see #getParamname()
   * @generated
   */
  void setParamname(Param value);

} // Parameter
