/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.constLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>System Invariant</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link umlrtsyntesizer.constLang.SystemInvariant#getName <em>Name</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.SystemInvariant#getInvariantExp <em>Invariant Exp</em>}</li>
 * </ul>
 *
 * @see umlrtsyntesizer.constLang.ConstLangPackage#getSystemInvariant()
 * @model
 * @generated
 */
public interface SystemInvariant extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getSystemInvariant_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.SystemInvariant#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Invariant Exp</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Invariant Exp</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invariant Exp</em>' containment reference.
   * @see #setInvariantExp(Expression)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getSystemInvariant_InvariantExp()
   * @model containment="true"
   * @generated
   */
  Expression getInvariantExp();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.SystemInvariant#getInvariantExp <em>Invariant Exp</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Invariant Exp</em>' containment reference.
   * @see #getInvariantExp()
   * @generated
   */
  void setInvariantExp(Expression value);

} // SystemInvariant
