/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.constLang;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Value</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link umlrtsyntesizer.constLang.Value#isMinues <em>Minues</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.Value#getValue <em>Value</em>}</li>
 *   <li>{@link umlrtsyntesizer.constLang.Value#getFixedPointValue <em>Fixed Point Value</em>}</li>
 * </ul>
 *
 * @see umlrtsyntesizer.constLang.ConstLangPackage#getValue()
 * @model
 * @generated
 */
public interface Value extends EObject
{
  /**
   * Returns the value of the '<em><b>Minues</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Minues</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Minues</em>' attribute.
   * @see #setMinues(boolean)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getValue_Minues()
   * @model
   * @generated
   */
  boolean isMinues();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.Value#isMinues <em>Minues</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Minues</em>' attribute.
   * @see #isMinues()
   * @generated
   */
  void setMinues(boolean value);

  /**
   * Returns the value of the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' attribute.
   * @see #setValue(int)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getValue_Value()
   * @model
   * @generated
   */
  int getValue();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.Value#getValue <em>Value</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' attribute.
   * @see #getValue()
   * @generated
   */
  void setValue(int value);

  /**
   * Returns the value of the '<em><b>Fixed Point Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Fixed Point Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fixed Point Value</em>' containment reference.
   * @see #setFixedPointValue(RealLiteral)
   * @see umlrtsyntesizer.constLang.ConstLangPackage#getValue_FixedPointValue()
   * @model containment="true"
   * @generated
   */
  RealLiteral getFixedPointValue();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.constLang.Value#getFixedPointValue <em>Fixed Point Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fixed Point Value</em>' containment reference.
   * @see #getFixedPointValue()
   * @generated
   */
  void setFixedPointValue(RealLiteral value);

} // Value
