/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.execTraces;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Bool Literal</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link umlrtsyntesizer.execTraces.BoolLiteral#getBool <em>Bool</em>}</li>
 * </ul>
 *
 * @see umlrtsyntesizer.execTraces.ExecTracesPackage#getBoolLiteral()
 * @model
 * @generated
 */
public interface BoolLiteral extends Literal
{
  /**
   * Returns the value of the '<em><b>Bool</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Bool</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Bool</em>' attribute.
   * @see #setBool(String)
   * @see umlrtsyntesizer.execTraces.ExecTracesPackage#getBoolLiteral_Bool()
   * @model
   * @generated
   */
  String getBool();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.execTraces.BoolLiteral#getBool <em>Bool</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Bool</em>' attribute.
   * @see #getBool()
   * @generated
   */
  void setBool(String value);

} // BoolLiteral
