/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.execTraces;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Exec Traces</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link umlrtsyntesizer.execTraces.ExecTraces#getComponentName <em>Component Name</em>}</li>
 *   <li>{@link umlrtsyntesizer.execTraces.ExecTraces#getNode <em>Node</em>}</li>
 *   <li>{@link umlrtsyntesizer.execTraces.ExecTraces#getEdge <em>Edge</em>}</li>
 * </ul>
 *
 * @see umlrtsyntesizer.execTraces.ExecTracesPackage#getExecTraces()
 * @model
 * @generated
 */
public interface ExecTraces extends EObject
{
  /**
   * Returns the value of the '<em><b>Component Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Component Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Component Name</em>' attribute.
   * @see #setComponentName(String)
   * @see umlrtsyntesizer.execTraces.ExecTracesPackage#getExecTraces_ComponentName()
   * @model
   * @generated
   */
  String getComponentName();

  /**
   * Sets the value of the '{@link umlrtsyntesizer.execTraces.ExecTraces#getComponentName <em>Component Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Component Name</em>' attribute.
   * @see #getComponentName()
   * @generated
   */
  void setComponentName(String value);

  /**
   * Returns the value of the '<em><b>Node</b></em>' containment reference list.
   * The list contents are of type {@link umlrtsyntesizer.execTraces.Node}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Node</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' containment reference list.
   * @see umlrtsyntesizer.execTraces.ExecTracesPackage#getExecTraces_Node()
   * @model containment="true"
   * @generated
   */
  EList<Node> getNode();

  /**
   * Returns the value of the '<em><b>Edge</b></em>' containment reference list.
   * The list contents are of type {@link umlrtsyntesizer.execTraces.Edge}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Edge</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Edge</em>' containment reference list.
   * @see umlrtsyntesizer.execTraces.ExecTracesPackage#getExecTraces_Edge()
   * @model containment="true"
   * @generated
   */
  EList<Edge> getEdge();

} // ExecTraces
