/*
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class ConstLangAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("umlrtsyntesizer/parser/antlr/internal/InternalConstLang.tokens");
	}
}
