/*
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import umlrtsyntesizer.parser.antlr.internal.InternalConstLangParser;
import umlrtsyntesizer.services.ConstLangGrammarAccess;

public class ConstLangParser extends AbstractAntlrParser {

	@Inject
	private ConstLangGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalConstLangParser createParser(XtextTokenStream stream) {
		return new InternalConstLangParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Context";
	}

	public ConstLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(ConstLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
