/**
 * generated by Xtext 2.19.0
 */
package umlrtsyntesizer;

import umlrtsyntesizer.ExecTracesStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class ExecTracesStandaloneSetup extends ExecTracesStandaloneSetupGenerated {
  public static void doSetup() {
    new ExecTracesStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
